### ISSUE TITLE
When i try to use the waymore i am getting this error **ERROR processCommonCrawlCollection 1: name 'process' is not defined**

### ISSUE THREAD

**Issue by RizwanSiDdiqu1** [xnl-h4ck3r/waymore#12]
Error:

ERROR processCommonCrawlCollection 1: name 'process' is not defined

![image](https://user-images.githubusercontent.com/72160000/183356294-14dd19aa-54a4-4a2b-bc34-a1a1a10978eb.png)

**Comment by xnl-h4ck3r** [comment]
Hi @RizwanSiDdiqu1 
I think I've spotted the issue here and the fix will be in the next version coming very soon. However, you should be able to remedy this problem now if you run `pip install psutil` (or `pip3 install psutil`, depends on your setup). Can you try and let me know if that solves the problem?
Thanks
Xnl
