### ISSUE TITLE
Update Speed on HTTP Response Download

### ISSUE THREAD

**Issue by MarcoZufferli** [xnl-h4ck3r/waymore#14]
Hello! 

It would be awesome to speed up all the download of all HTTP Response archived, if we need to download a huge HTTP Response it could become very slow,  i dont know how it is written the tool but maybe a Threaded WGET of that files it would be helpful.

Thank you!

**Comment by xnl-h4ck3r** [comment]
Hi @MarcoZufferli 
Thanks for taking the time to log an issue. It already uses parallel processes to download the archived responses. The `-p`/`--processes` determines the number of processes. However, this defaults to 3 and is intentionally low to be kind to the archive,org servers that aren't geared up for huge volume. This tool is slow, and it will be because of the API's it uses, but it is a tool designed for maximum coverage rather than speed.
Kind regards
Xnl
