### ISSUE TITLE
it lasts too long

### ISSUE THREAD

**Issue by Teicu** [xnl-h4ck3r/waymore#15]
Hi, 

It's not a bug but rather a question. There are sites where I waited 4-5 hours for it to finish and finally I shut everything down. For example a google subdomain or any other larger site. Is there any possibility to stop and obviously get the result even if the scanner hasn't finished all the steps? 
 
Thanks

**Comment by xnl-h4ck3r** [comment]
Hi @Teicu 
If you press Ctrl-C to end the program and wait a minute it should save everything it has so far and end cleanly. Did you try that?
I am going to be making a change so that for responses it will carry on where it finished last time if you stop it or it gets Killed for some reason.
Regards
Xnl

**Comment by xnl-h4ck3r** [comment]
Hi @Teicu. I haven't heard back from you so I will close this issue now.
KInd regards
Xnl
