### ISSUE TITLE
urlscan don't fetch all results

### ISSUE THREAD

**Issue by molitona** [xnl-h4ck3r/waymore#28]
```
python waymore.py -i 000webhost.com -mode U -p 1 -xwm -xcc -xav | tee -a urlscan.txt 
```

got only 233/2911 result while i use an api key and there is enough credit as you see here https://urlscan.io/user/quotas/ while you're authenticated to you free account ?

![Screenshot from 2023-08-31 16-09-35](https://github.com/xnl-h4ck3r/waymore/assets/35532337/a2aee141-7f57-442d-9d5b-2ad61a369671)

config 
```
FILTER_CODE: 404,301,302
FILTER_MIME: text/css,image/jpeg,image/jpg,image/png,image/svg+xml,image/gif,image/tiff,image/webp,image/bmp,image/vnd,image/x-icon,image/vnd.microsoft.icon,font/ttf,font/woff,font/woff2,font/x-woff2,font/x-woff,font/otf,audio/mpeg,audio/wav,audio/webm,audio/aac,audio/ogg,audio/wav,audio/webm,video/mp4,video/mpeg,video/webm,video/ogg,video/mp2t,video/webm,video/x-msvideo,video/x-flv,application/font-woff,application/font-woff2,application/x-font-woff,application/x-font-woff2,application/vnd.ms-fontobject,application/font-sfnt,application/vnd.android.package-archive,binary/octet-stream,application/octet-stream,application/pdf,application/x-font-ttf,application/x-font-otf,video/webm,video/3gpp,application/font-ttf,audio/mp3,audio/x-wav,image/pjpeg,audio/basic
FILTER_URL: .css,.jpg,.jpeg,.png,.svg,.img,.gif,.mp4,.flv,.ogv,.webm,.webp,.mov,.mp3,.m4a,.m4p,.scss,.tif,.tiff,.ttf,.otf,.woff,.woff2,.bmp,.ico,.eot,.htc,.rtf,.swf,.image,/image,/img,/css,/wp-json,/wp-content,/wp-includes,/theme,/audio,/captcha,/font,node_modules,/jquery,/bootstrap
#FILTER_KEYWORDS: admin,login,logon,signin,register,dashboard,portal,ftp,cpanel,panel,.js,api,robots.txt,graph,gql
URLSCAN_API_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
CONTINUE_RESPONSES_IF_PIPED: True
```

**Comment by molitona** [comment]
the 1 minute rate limit isn't exceeded. I was checking https://urlscan.io/user/quotas/ while the script is running.

even tried gau tool before it with proxyfying to burp. the 1 minute rate limit isn't exceeded too but, the results are few also?

**Comment by xnl-h4ck3r** [comment]
Hi @molitona. Thanks for raising this and apologies for the problem. Can you run it again  and use the `-v` flag and let me know if there are any errors of any kind shown?
Are you using a paid API key?
You said you "got only 233/2911 result"... where does it say that there are 2911 total results? Is that on the https://urlscan.io/search/ page?
Thanks

**Comment by xnl-h4ck3r** [comment]
Hi @molitona. I've just noticed that although you are searching for `000webhost.com` the URLScan site actually returns most URLs for a different domain of `000webhostapp.com`. I'm not sure why it does that! That cvould be why you don't get all the links you are expecting?

**Comment by molitona** [comment]
> Hi @molitona. Thanks for raising this and apologies for the problem. Can you run it again and use the `-v` flag and let me know if there are any errors of any kind shown? Are you using a paid API key? You said you "got only 233/2911 result"... where does it say that there are 2911 total results? Is that on the https://urlscan.io/search/ page? Thanks

yeah on https://urlscan.io/search/ says 2911
i'm using api key of sign-up. it can fetch all 2911 results as i explained

**Comment by molitona** [comment]
retested now got 221/2918 and didn't exceed quota

![d](https://github.com/xnl-h4ck3r/waymore/assets/35532337/37842d82-80f9-4d79-bea7-b71d4cb35795)

**Comment by xnl-h4ck3r** [comment]
Hi @molitona 
When I search on the website, I see that it gets 10000+ results and only shows 100 at a time. 
![image](https://github.com/xnl-h4ck3r/waymore/assets/84544946/a34bd68c-eca4-4272-9d22-b01ed29e5b8e)
So where do you see the 221/2918?
A.lso, as mentioned before, the results seem to include domains that don't match the search term. There are only 2 unique URLs for the actual search term within the first 100 shown, and they are:
www.000webhost.com/migrate?static=true
files.000webhost.com/

So in the same way when waymore is run, there are not many results because most of them do not match the domain that is passed to waymore.

Is that not the case in the results that you see on urlscan.io?

**Comment by xnl-h4ck3r** [comment]
> Hi @molitona When I search on the website, I see that it gets 10000+ results and only shows 100 at a time. ![image](https://user-images.githubusercontent.com/84544946/265225436-a34bd68c-eca4-4272-9d22-b01ed29e5b8e.png) So where do you see the 221/2918? A.lso, as mentioned before, the results seem to include domains that don't match the search term. There are only 2 unique URLs for the actual search term within the first 100 shown, and they are: [www.000webhost.com/migrate?static=true](http://www.000webhost.com/migrate?static=true) files.000webhost.com/
> 
> So in the same way when waymore is run, there are not many results because most of them do not match the domain that is passed to waymore.
> 
> Is that not the case in the results that you see on urlscan.io?

HI @molitona, I know it's been a long time since you raised this, but wasn't sure if you had seen my response. Was it the case that on the urlscan site itself, it was giving you lots of results that weren't for the domain you asked for? Do you beliebve there is still a problem with waymore for this, or can I close this issue? Thanks

**Comment by molitona** [comment]
hello, sorry didn't see the response

use `page.domain:000webhost.com` query to get only *.000webhost.com links

**Comment by xnl-h4ck3r** [comment]
Hi @molitona. Thank you for getting back to me again. I can see there are 3034. It's difficult sorting this problem out because I get rate limited very quickly with no API key. I'm hoping to get this problem fixed this week though. Sorry its taken so long!

**Comment by xnl-h4ck3r** [comment]
Hi @molitona. If you look at https://urlscan.io/search/#page.domain%3A000webhost.com most of the results are for 000webhostapp.com and not 000webhost.com which is why they are not inclued in the results because its a different domain. So I think waymore is working correctly. Do you disagree, or can I close the issue? Thanks

**Comment by molitona** [comment]
hello @xnl-h4ck3r,
i'm closing this now. i think it's probably not the case with this apex domain as there is many duplicate values too. i'll reply to this thread in the future if something found with 100% certainty!

**Comment by xnl-h4ck3r** [comment]
Hi @molitona . No problem, thanks!
