### ISSUE TITLE
scanning freeze on Getting links from the latest 3 commoncrawl.org index collections

### ISSUE THREAD

**Issue by skalvin** [xnl-h4ck3r/waymore#37]
from 2 days the tool not working like before it freeze on 

Links found on Wayback Machine (archive.org): 657  
Getting links from the latest 3 commoncrawl.org index collections (this can take a while for some domains)...

note: i try it with URLSCAN_API_KEY & VIRUSTOTAL_API_KEY and without API key it freeze on both mode

anything wrong?

**Comment by xnl-h4ck3r** [comment]
Hi @skalvin 
Thanks for using waymore and taking the time to raise the issue.
It looks like the problem is related to Common Crawl. They are returning `504 Gateway Time-out` errors when I try to check their indexes manually. Becaue of the way connections are retried many times (which was advice from Common Crawl), it is taking a long time for waymore to stop on the error, so hangs for a very long time. 
In the meantime, use `-xcc` to exclude Common Crawl and everything else works ok. I will try to get a change done today that will at least error properly if Common Crawl fails with 504 so continues with the rest.
Many thanks

**Comment by xnl-h4ck3r** [comment]
Hi @skalvin. I've released a new version now. It should not freeze indefintiley if Common Crawl have 504 errors now. Hopefully they will sort out their issues soon 🤞

**Comment by skalvin** [comment]
Thanks a lot for the great tool and the wonderful fast communication

the issue now solved with -xcc

Best Regards,,

**Comment by xnl-h4ck3r** [comment]
Glad to help! Keep an eye on my twitter and I'll update when Common Crawl have fixed their problems and you can remove `-xcc` again :)
